#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from collections import deque
q = deque(maxlen=3)
print(q)
q.append(1)
q.append(2)
print(q)
q.pop()
q.insert(1, 0)
q.append(3)
q.append(4)
print(q)
q.insert(5, 5)
print(q)

qq = deque()
qq = q.copy()
print(qq, q.maxlen)

q = deque("asd")
print(q)
q.extend("qw")
q.extendleft("zx")
print(list(q))
q.rotate(-1)
print(q)
q.reverse()
print(q)
print(q.maxlen, q.index("a"), q.count("a"))
q.clear()
print(q, q.maxlen)
