#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import re
line = 'asdf   fjdk;  afed, fjek,asdf,      foo'
words_only = re.split(r'[;,\s]\s*', line)
words_with = re.split(r'(;|,|\s)\s*', line)
words_only_group = re.split(r'(?:;|,|\s)\s*', line)
print("{0}\n{1}\n{2}".format(words_only, words_with, words_only_group))

info = "Today is 16/10/2016. That day is 4/27/2017."
date_pat = re.compile(r'\d+/\d+/\d+')
print(date_pat.findall(info))
date_pat = re.compile(r'(\d+)/(\d+)/(\d+)')
print(date_pat.findall(info), date_pat.finditer(info))
for m in date_pat.finditer(info):
    print(m.groups(), m.group(0), m.group(1))
